// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/domain_events.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	events "github.com/forest-shadow/calendar/internal/events"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockeventService is a mock of eventService interface.
type MockeventService struct {
	ctrl     *gomock.Controller
	recorder *MockeventServiceMockRecorder
}

// MockeventServiceMockRecorder is the mock recorder for MockeventService.
type MockeventServiceMockRecorder struct {
	mock *MockeventService
}

// NewMockeventService creates a new mock instance.
func NewMockeventService(ctrl *gomock.Controller) *MockeventService {
	mock := &MockeventService{ctrl: ctrl}
	mock.recorder = &MockeventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventService) EXPECT() *MockeventServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockeventService) Create(ctx context.Context, event events.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockeventServiceMockRecorder) Create(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockeventService)(nil).Create), ctx, event)
}

// Delete mocks base method.
func (m *MockeventService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockeventServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockeventService)(nil).Delete), ctx, id)
}

// DeleteOldEvents mocks base method.
func (m *MockeventService) DeleteOldEvents(ctx context.Context, date time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldEvents", ctx, date)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOldEvents indicates an expected call of DeleteOldEvents.
func (mr *MockeventServiceMockRecorder) DeleteOldEvents(ctx, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldEvents", reflect.TypeOf((*MockeventService)(nil).DeleteOldEvents), ctx, date)
}

// Get mocks base method.
func (m *MockeventService) Get(ctx context.Context, id uuid.UUID) (events.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(events.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockeventServiceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockeventService)(nil).Get), ctx, id)
}

// GetList mocks base method.
func (m *MockeventService) GetList(ctx context.Context, from, to time.Time) ([]events.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, from, to)
	ret0, _ := ret[0].([]events.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockeventServiceMockRecorder) GetList(ctx, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockeventService)(nil).GetList), ctx, from, to)
}

// GetRecentEvents mocks base method.
func (m *MockeventService) GetRecentEvents(ctx context.Context, from time.Time) (*[]events.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentEvents", ctx, from)
	ret0, _ := ret[0].(*[]events.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentEvents indicates an expected call of GetRecentEvents.
func (mr *MockeventServiceMockRecorder) GetRecentEvents(ctx, from interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentEvents", reflect.TypeOf((*MockeventService)(nil).GetRecentEvents), ctx, from)
}

// MarkEventsAsNotified mocks base method.
func (m *MockeventService) MarkEventsAsNotified(ctx context.Context, ids []uuid.UUID, notifiedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventsAsNotified", ctx, ids, notifiedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEventsAsNotified indicates an expected call of MarkEventsAsNotified.
func (mr *MockeventServiceMockRecorder) MarkEventsAsNotified(ctx, ids, notifiedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventsAsNotified", reflect.TypeOf((*MockeventService)(nil).MarkEventsAsNotified), ctx, ids, notifiedAt)
}

// Update mocks base method.
func (m *MockeventService) Update(ctx context.Context, id uuid.UUID, event events.UpdateEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockeventServiceMockRecorder) Update(ctx, id, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockeventService)(nil).Update), ctx, id, event)
}
